# SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
# SPDX-License-Identifier: GPL-2.0-only

# Carbonio Certbot directories
# See tmpfiles.d(5) for format

d /opt/zextras/.well-known/acme-challenge - zextras zextras
d /opt/zextras/common/certbot/etc/letsencrypt - zextras zextras
d /var/lib/carbonio-letsencrypt - zextras zextras
d /var/log/carbonio/letsencrypt 0700 zextras zextras

Z /opt/zextras/.well-known - zextras zextras
Z /opt/zextras/common/certbot/etc/letsencrypt 0750 zextras zextras
