d /opt/zextras/.well-known/acme-challenge - zextras zextras -
Z /opt/zextras/.well-known - zextras zextras -
d /opt/zextras/common/certbotetc/letsencrypt - zextras zextras -
d /var/lib/carbonio-letsencrypt - zextras zextras -
d /var/log/carbonio/letsencrypt 0700 zextras zextras -
